### ISSUE TITLE
Add build badges

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/meta-search-engine#1]
Familiarize yourself with badges you can find on https://shields.io/  they are used to show the status of many github projects.

Add at least
- A travis build badge
- A dockerhub automated build status showing success or failure

Add them to the README.md file right below the first heading.

**Comment by suknuk** [comment]
Hello, I am new in using Git/GitHub with multiple people, so not quite sure if I did everything correct - I added the requested badges in the README.md file and made a pull request. Please let me know if everything is satisfactory

**Comment by niccokunzmann** [comment]
Todo to close: use docker build badge of schulcloud/meta-search-engine

**Comment by niccokunzmann** [comment]
@suknuk Thanks for working on it. I hope you had a great time. I am closing this now as it is resolved.

**Comment by suknuk** [comment]
Yes, thank you for your feedback :)
