### ISSUE TITLE
fix travis tests

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/meta-search-engine#4]
Currenty, the travis tests are failing: https://travis-ci.org/schul-cloud/meta-search-engine
Please fix that.

Idea:
- in travis, build the docker container
- run the container
- test against the running container

**Comment by suknuk** [comment]
Hello, 
I changed the .travis.yml file according to your idea. I was however unable transform the after_failure part to display the access/error logs from the docker container.
Can you tell me if everything is okay for a pull request or do you want me to change something in the travis file?

**Comment by niccokunzmann** [comment]
Hi @suknuk, this looks good.
Would you like to create a pull-request?

I do not know if getting this after failure files running is important. I think, the server should print out everything into the docker log. These files should not be used as I would expect the command

    docker log meta-search-engine-container

to display all information. (It could also be docker logs, maybe docker start instead of docker run .. I do not know :) ).
What do you think?

**Comment by suknuk** [comment]
Hello @niccokunzmann,
I just started using Docker, so I am not at all an expert, but I believe the order for Docker containers is the following:
```
docker run --name [NAME] [CONTAINER]
docker stop [NAME]
docker start [NAME]
```
I also added the docker logs in case of failure for the Travis tests in the pull request

**Comment by niccokunzmann** [comment]
@suknuk Thanks, I am really greatful. I tried a lot to get the tests running natively but it did not work.
If you like to contribute further, I invite you to: https://github.com/schul-cloud/meta-search-engine/invitations
We have a rule that we do not merge our own pull-requests.

The meta-search-engine is part of a greater project to scale up the content search: https://github.com/schul-cloud/schulcloud-content/projects/1 and this issue is the reason why it was created:
https://github.com/schul-cloud/schulcloud-content/issues/2

I should write this into the README^^

Let me know if you need anything else or if I can help somewhere. You can still comment if I close, I think.

**Comment by suknuk** [comment]
Thanks @niccokunzmann,
Even though I have no experience in php, I would like to try to resolve Issue #2. Currently on Travis and my local machine, the following command:
```
curl -i 'http://localhost:8000/?Q=einstein'
```
results in no actual data being returned [result](https://gist.github.com/suknuk/5476c4d3df19d39d257a8a27dcbd780c)
Ideally, I would like to see some data being returned before beginning to work on the issue - any idea how I could achieve this?

**Comment by niccokunzmann** [comment]
Let's talk in #2 about it.
